### ISSUE TITLE
Control instead of replace WM

### ISSUE THREAD

**Issue by hoschi** [santigimeno/node-ewmh#20]
is it possible to control an existing WM (Xmonad in my case) instead of replacing it? Like the tool `wmctl` . I get the 'bad access' error when try to create an EWMH instance.

**Comment by sidorares** [comment]
what kind of control? In some way or another all EWMH protocol is the way of controlling wm

**Comment by santigimeno** [comment]
I guess the problem @hoschi is referring to is that the module automatically tries to set the `SubstructureRedirect` mask in the `root` window and having a WM launched causes the error.
@hoschi What happens if you ignore that error? Is the module still usable for you? i didn't design the module for this but maybe it just works. Of course you will never receive any events but most of the API functions could work

**Comment by hoschi** [comment]
@santigimeno you guessed right :)
Hm, I'm not sure if I understand 'if you ignore that error' :( 
I took these steps:
- deleted this lines -> https://github.com/santigimeno/node-ewmh/blob/master/lib/ewmh.js#L13-L27
- start example script `node example/example.js` (no errors \o/ )
- but then it doesn't log anything when I cycle through my desktops and it doesn't change the desktop to number 4, so I think it doesn't work, at least not with my steps

**Comment by santigimeno** [comment]
@hoschi What exactly would you expect it to do?
If you want some tool ala `wmctrl` you would need to send the appropriate `ClientMessage`'s as defined in the `EWMH` specification so they can be handled by the WM.
The ewmh object has a `send_client_message` function: https://github.com/santigimeno/node-ewmh/blob/master/lib/ewmh.js#L129 that can help you accomplish that. There are no specific functions for actions like: switch desktops, move windows, etc, as this library was first designed to be used by a WM implementation, but they should be fairly easy to implement by using the `send_client_message` function

**Comment by hoschi** [comment]
> but then it doesn't log anything when I cycle through my desktops

I expected that it still react on events, because of this line https://github.com/santigimeno/node-ewmh/blob/master/lib/ewmh.js#L12

Also I thought it can still change the window props to e.g. switch a desktop. I look into sending client mesages instead, thanks for this info.

**Comment by santigimeno** [comment]
Sure, but as you're not acting as a WM, you had to remove the following lines that change the `root` `eventMask` so no events are generated.

My understanding is that in the `EWMH` specification x11 clients send `ClientMessage`'s and a `EWMH` reacts to those messages. For example a client can send a `_NET_WM_DESKTOP` to move a window to a specific desktop and the WM will try to honor it.

This module is intended to be used by a WM implementation: if a `_NET_WM_DESKTOP` `ClientMessage` is received, it will emit an event so that the WM can perform the action.

I think that what you're trying to implement is the client-side part: sending `ClientMessage`'s so that the WM you're using reacts to them.

Does it make any sense to you?

**Comment by hoschi** [comment]
Thank you for this explanation, this makes clearer what happened when I removed the lines.
